"""Localization resources for the Minesweeper client."""
from __future__ import annotations

import os


_DATA_ROOT = os.getenv("LOCALAPPDATA") or os.getenv("APPDATA") or os.path.expanduser("~")
_DATA_DIR = os.path.join(_DATA_ROOT, "CyberMinesweeper")
_LANG_FILE = os.path.join(_DATA_DIR, "lang_pref.txt")

_ZH = {
    "title": "扫雷",
    "login": "登录账号",
    "register": "创建账号",
    "username": "用户名",
    "password": "密码",
    "confirm_pwd": "确认密码",
    "btn_login": "进入大厅",
    "btn_register": "创建账号",
    "no_account": "还没有账号？",
    "has_account": "已有账号？",
    "to_register": "创建新账号",
    "to_login": "返回登录",
    "warn_empty": "请输入用户名和密码。",
    "login_fail": "登录失败",
    "login_user_missing": "没有找到这个账号，请检查用户名或先创建账号。",
    "login_password_wrong": "密码不正确。账号存在，密码没有被重置。",
    "reg_fail": "注册失败",
    "reg_ok": "注册成功",
    "pwd_mismatch": "两次输入的密码不一致。",
    "user_exists": "用户名已存在。",
    "pwd_short": "密码至少需要 4 个字符。",
    "user_short": "用户名至少需要 2 个字符。",
    "pwd_hint": "密码（至少 4 位）",
    "menu_title": "作战大厅",
    "welcome": "欢迎，{}",
    "lobby_kicker": "扫雷 / 作战大厅",
    "records_kicker": "战绩 / 系统",
    "control_kicker": "扫雷 / 操作",
    "mode_label": "模式",
    "mode_training": "训练",
    "mode_advanced": "进阶",
    "mode_extreme": "极限",
    "window_title": "{} · {} · {}",
    "auth_fallback": "扫雷",
    "diff_easy": "训练 9x9",
    "diff_medium": "进阶 27x27",
    "diff_hard": "极限 81x81",
    "desc_easy": "10 雷 / 入门热身",
    "desc_medium": "100 雷 / 高压推进",
    "desc_hard": "800 雷 / 长线作战",
    "btn_start": "启动作战",
    "btn_ranking": "战绩榜",
    "btn_logout": "退出登录",
    "btn_account": "玩家档案",
    "btn_back": "返回",
    "btn_restart": "重开",
    "btn_lobby": "返回大厅",
    "btn_result_records": "查看战绩",
    "game_over": "任务失败",
    "game_over_msg": "你触发了地雷，任务终止。",
    "win_title": "任务完成",
    "win_msg": "清扫完成。\n\n模式：{}\n用时：{}\n\n成绩已写入战绩榜。",
    "win_msg_with_mode": "清扫完成。\n\n{}：{}\n用时：{}\n\n成绩已写入战绩榜。",
    "rank_title": "战绩榜",
    "my_records": "我的记录",
    "rank_col": "排名",
    "user_col": "玩家",
    "time_col": "用时",
    "date_col": "完成时间",
    "no_data": "暂无记录",
    "no_records": "暂无个人记录",
    "difficulty_col": "模式",
    "current_user": "当前玩家：{}",
    "logout_confirm": "确定退出当前账号？",
    "quit_confirm": "确定退出游戏？",
    "easy_title": "训练 9x9",
    "medium_title": "进阶 27x27",
    "hard_title": "极限 81x81",
    "mines": "剩余雷数",
    "btn_close": "关闭",
    "language": "语言",
    "time_label": "计时",
    "status_local_loaded": "本地战绩已加载 / 云端同步中",
    "status_cloud_done": "本地战绩已加载 / 云端同步完成",
    "status_cloud_failed": "本地战绩已加载 / 在线战绩暂不可用",
    "control_hint": "左键翻开 / 右键标记 / 中键·双击数字快速展开",
    "zoom_fit": "重置缩放",
    "profile_label": "玩家档案",
    "profile_subtitle": "账户概览、最佳成绩和最近战局",
    "profile_total_matches": "总局数",
    "profile_wins": "胜场",
    "profile_losses": "败局",
    "profile_win_rate": "胜率",
    "profile_recent_title": "最近战绩",
    "profile_no_recent": "暂无最近战绩",
    "profile_switch_account": "切换账号",
    "match_win": "胜利",
    "match_fail": "失败",
    "records_label": "战绩同步",
    "auth_kicker": "MINESWEEPER / ACCESS NODE",
    "auth_status": "本地档案在线 / 离线排行可用",
    "auth_ready": "输入账号后直接进入作战大厅。",
    "quick_controls": "R 重开 / Esc 返回 / 右键标记",
    "lobby_controls": "选择模式进入雷区 / 档案查看账号 / 战绩榜查看本地与云端记录",
    "best_label": "BEST",
    "ops_label": "RUNS",
    "no_record_short": "NO RECORD",
    "clearance_label": "CLEARANCE",
    "flags_label": "FLAGS",
    "result_summary": "行动报告",
    "result_saved": "战绩已写入本地档案",
    "result_failed_tip": "雷区已暴露，建议立即重开校准路径。",
    "result_win_tip": "清扫完成，成绩已记录。",
    "personal_best_title": "个人最佳",
    "menu_subtitle": "选择作战模块，进入雷区扫描。",
    "lobby_profile_title": "COMBAT ID",
    "lobby_profile_subtitle": "当前身份和个人战绩摘要",
    "lobby_profile_open": "打开档案中心",
    "lobby_record_open": "打开战绩榜",
    "lobby_records_title": "个人战绩",
    "lobby_records_subtitle": "查看各作战模式的最佳完成时间。",
    "grid_label": "GRID",
    "mine_density": "DENSITY",
    "mine_count_label": "MINES",
    "threat_label": "THREAT",
    "threat_low": "LOW",
    "threat_medium": "HIGH",
    "threat_high": "EXTREME",
    "sector_label": "SECTOR",
    "board_status_ready": "Minefield idle",
    "board_status_live": "Scan active",
    "board_status_failed": "Mission failed",
    "board_status_clear": "Sector clear",
    "rank_subtitle": "Local records show first while cloud data merges in the background.",
    "rank_empty_marker": "NO SIGNAL",
    "result_retry_tip": "Press R to restart immediately, or return to the lobby.",
}

_EN = {
    "title": "Minesweeper",
    "login": "Sign In",
    "register": "Create Account",
    "username": "Username",
    "password": "Password",
    "confirm_pwd": "Confirm Password",
    "btn_login": "Enter Lobby",
    "btn_register": "Create Account",
    "no_account": "No account yet?",
    "has_account": "Already have an account?",
    "to_register": "Create Account",
    "to_login": "Back to Sign In",
    "warn_empty": "Please enter a username and password.",
    "login_fail": "Sign In Failed",
    "login_user_missing": "No account found. Check the username or create it first.",
    "login_password_wrong": "Password is incorrect. The account exists and was not reset.",
    "reg_fail": "Registration Failed",
    "reg_ok": "Registration Complete",
    "pwd_mismatch": "Passwords do not match.",
    "user_exists": "Username already exists.",
    "pwd_short": "Password must be at least 4 characters.",
    "user_short": "Username must be at least 2 characters.",
    "pwd_hint": "Password (min 4 chars)",
    "menu_title": "Operations Lobby",
    "welcome": "Welcome, {}",
    "lobby_kicker": "MINESWEEPER / LOBBY",
    "records_kicker": "RECORDS / SYSTEM",
    "control_kicker": "MINESWEEPER / CONTROL",
    "mode_label": "MODE",
    "mode_training": "TRAINING",
    "mode_advanced": "ADVANCED",
    "mode_extreme": "EXTREME",
    "window_title": "{} · {} · {}",
    "auth_fallback": "MINE",
    "diff_easy": "Training 9x9",
    "diff_medium": "Advanced 27x27",
    "diff_hard": "Extreme 81x81",
    "desc_easy": "10 mines / warm-up run",
    "desc_medium": "100 mines / high pressure",
    "desc_hard": "800 mines / long operation",
    "btn_start": "Launch",
    "btn_ranking": "Records",
    "btn_logout": "Logout",
    "btn_account": "Profile",
    "btn_back": "Back",
    "btn_restart": "Restart",
    "btn_lobby": "Lobby",
    "btn_result_records": "Records",
    "game_over": "Mission Failed",
    "game_over_msg": "You triggered a mine. Mission terminated.",
    "win_title": "Mission Complete",
    "win_msg": "Clear complete.\n\nMode: {}\nTime: {}\n\nScore saved to records.",
    "win_msg_with_mode": "{}: {}\nTime: {}\n\nScore saved to records.",
    "rank_title": "Records",
    "my_records": "My Records",
    "rank_col": "Rank",
    "user_col": "Player",
    "time_col": "Time",
    "date_col": "Completed",
    "no_data": "No records",
    "no_records": "No personal records",
    "difficulty_col": "Mode",
    "current_user": "Current player: {}",
    "logout_confirm": "Log out of this account?",
    "quit_confirm": "Quit the game?",
    "easy_title": "Training 9x9",
    "medium_title": "Advanced 27x27",
    "hard_title": "Extreme 81x81",
    "mines": "Mines",
    "btn_close": "Close",
    "language": "Language",
    "time_label": "Time",
    "status_local_loaded": "Local records loaded / cloud sync running",
    "status_cloud_done": "Local records loaded / cloud sync complete",
    "status_cloud_failed": "Local records loaded / online records unavailable",
    "control_hint": "Left reveal / Right flag / Middle-click or double-click number",
    "zoom_fit": "Reset zoom",
    "profile_label": "Profile",
    "profile_subtitle": "Account overview, best times, and recent runs.",
    "profile_total_matches": "Matches",
    "profile_wins": "Wins",
    "profile_losses": "Losses",
    "profile_win_rate": "Win Rate",
    "profile_recent_title": "Recent Runs",
    "profile_no_recent": "No recent runs yet",
    "profile_switch_account": "Switch Account",
    "match_win": "WIN",
    "match_fail": "FAIL",
    "records_label": "Record Sync",
    "auth_kicker": "MINESWEEPER / ACCESS NODE",
    "auth_status": "Local profile online / offline records enabled",
    "auth_ready": "Enter credentials and jump straight into the operations lobby.",
    "quick_controls": "R restart / Esc back / Right-click flag",
    "lobby_controls": "Choose a mode / Profile for account / Records for local and cloud runs",
    "best_label": "BEST",
    "ops_label": "RUNS",
    "no_record_short": "NO RECORD",
    "clearance_label": "CLEARANCE",
    "flags_label": "FLAGS",
    "result_summary": "Action Report",
    "result_saved": "Score saved to local profile",
    "result_failed_tip": "Minefield exposed. Restart and recalibrate the path.",
    "result_win_tip": "Sweep complete. Record captured.",
    "personal_best_title": "Personal Best",
    "menu_subtitle": "Choose an operation module and enter the minefield.",
    "lobby_profile_title": "COMBAT ID",
    "lobby_profile_subtitle": "Current identity and personal record snapshot.",
    "lobby_profile_open": "Open Profile Center",
    "lobby_record_open": "Open Records",
    "lobby_records_title": "PERSONAL RECORDS",
    "lobby_records_subtitle": "Your best completion time in each operation mode.",
    "grid_label": "GRID",
    "mine_density": "DENSITY",
    "mine_count_label": "MINES",
    "threat_label": "THREAT",
    "threat_low": "LOW",
    "threat_medium": "HIGH",
    "threat_high": "EXTREME",
    "sector_label": "SECTOR",
    "board_status_ready": "Minefield idle",
    "board_status_live": "Scan active",
    "board_status_failed": "Mission failed",
    "board_status_clear": "Sector clear",
    "rank_subtitle": "Local records show first while cloud data merges in the background.",
    "rank_empty_marker": "NO SIGNAL",
    "result_retry_tip": "Press R to restart immediately, or return to the lobby.",
}

def _locale(overrides: dict[str, str]) -> dict[str, str]:
    values = dict(_EN)
    values.update(overrides)
    return values


_ZH_TW = dict(_ZH)
_ZH_TW.update({
    "title": "掃雷",
    "language": "語言",
    "auth_status": "本地檔案在線 / 離線排行可用",
})

_LZH = dict(_ZH)
_LZH.update({
    "title": "掃雷",
    "login": "入局",
    "register": "立籍",
    "username": "名號",
    "password": "密語",
    "confirm_pwd": "復書密語",
    "btn_login": "入廳",
    "btn_register": "立籍",
    "no_account": "尚未立籍乎？",
    "has_account": "已有籍乎？",
    "to_register": "立新籍",
    "to_login": "返入局",
    "warn_empty": "名號、密語，皆須書之。",
    "login_fail": "入局未成",
    "login_user_missing": "查無此籍。請核名號，或先立籍。",
    "login_password_wrong": "密語不合。名號尚存，未曾更易。",
    "reg_fail": "立籍未成",
    "reg_ok": "立籍已成",
    "pwd_mismatch": "兩書密語未同。",
    "user_exists": "此名號已有主。",
    "pwd_short": "密語至少四字。",
    "user_short": "名號至少二字。",
    "pwd_hint": "密語（至少四字）",
    "menu_title": "作戰廳",
    "welcome": "恭迎，{}",
    "lobby_kicker": "掃雷 / 作戰廳",
    "records_kicker": "戰績 / 冊籍",
    "control_kicker": "掃雷 / 操作",
    "mode_label": "式",
    "mode_training": "習練",
    "mode_advanced": "進階",
    "mode_extreme": "窮極",
    "window_title": "{} · {} · {}",
    "auth_fallback": "掃雷",
    "diff_easy": "習練 9x9",
    "diff_medium": "進階 27x27",
    "diff_hard": "窮極 81x81",
    "desc_easy": "十雷 / 入門試手",
    "desc_medium": "百雷 / 臨危而進",
    "desc_hard": "八百雷 / 長驅久戰",
    "btn_start": "出戰",
    "btn_ranking": "戰績榜",
    "btn_logout": "出局",
    "btn_account": "名籍",
    "btn_back": "返",
    "btn_restart": "重開",
    "btn_lobby": "返廳",
    "btn_result_records": "觀戰績",
    "game_over": "局敗",
    "game_over_msg": "觸雷，局遂敗。",
    "win_title": "局成",
    "win_msg": "掃除已畢。\n\n式：{}\n用時：{}\n\n戰績已錄。",
    "win_msg_with_mode": "{}：{}\n用時：{}\n\n戰績已錄。",
    "rank_title": "戰績榜",
    "my_records": "吾之紀錄",
    "rank_col": "名次",
    "user_col": "玩家",
    "time_col": "用時",
    "date_col": "成時",
    "no_data": "暫無紀錄",
    "no_records": "暫無己之紀錄",
    "difficulty_col": "式",
    "current_user": "在局者：{}",
    "logout_confirm": "確欲出局乎？",
    "quit_confirm": "確欲離局乎？",
    "easy_title": "習練 9x9",
    "medium_title": "進階 27x27",
    "hard_title": "窮極 81x81",
    "mines": "餘雷",
    "btn_close": "閉",
    "language": "語言",
    "time_label": "計時",
    "status_local_loaded": "本地戰績已載 / 雲端方並",
    "status_cloud_done": "本地戰績已載 / 雲端並訖",
    "status_cloud_failed": "本地戰績已載 / 雲端未通",
    "control_hint": "左鍵開格 / 右鍵立幟 / 中鍵·雙擊數字速展",
    "zoom_fit": "復原",
    "profile_label": "名籍",
    "profile_subtitle": "籍之大概、上佳戰績與近日戰局",
    "profile_total_matches": "總局",
    "profile_wins": "勝局",
    "profile_losses": "敗局",
    "profile_win_rate": "勝率",
    "profile_recent_title": "近日戰績",
    "profile_no_recent": "暫無近日戰績",
    "profile_switch_account": "易籍",
    "match_win": "勝",
    "match_fail": "敗",
    "records_label": "戰績並合",
    "auth_kicker": "掃雷 / 入局之樞",
    "auth_status": "本地檔案可用 / 離線榜單可覽",
    "auth_ready": "書號入局，徑入作戰廳。",
    "quick_controls": "R 重開 / Esc 返 / 右鍵立幟",
    "lobby_controls": "擇式入雷區 / 名籍察己 / 戰績榜覽本地及雲端",
    "best_label": "上佳",
    "ops_label": "局",
    "no_record_short": "無紀錄",
    "clearance_label": "掃除率",
    "flags_label": "幟數",
    "result_summary": "戰報",
    "result_saved": "戰績已錄本地",
    "result_failed_tip": "雷區既露，宜即重開，重校其徑。",
    "result_win_tip": "掃除既訖，戰績已錄。",
    "personal_best_title": "己之上佳",
    "menu_subtitle": "擇一作戰之式，入雷區掃除。",
    "lobby_profile_title": "戰號",
    "lobby_profile_subtitle": "當前身分與己身戰績略要",
    "lobby_profile_open": "啟名籍",
    "lobby_record_open": "啟戰績榜",
    "lobby_records_title": "己之戰績",
    "lobby_records_subtitle": "觀各式上佳完局之時",
    "grid_label": "格",
    "mine_density": "密度",
    "mine_count_label": "雷數",
    "threat_label": "危",
    "threat_low": "低",
    "threat_medium": "高",
    "threat_high": "極",
    "sector_label": "方域",
    "board_status_ready": "雷區未動",
    "board_status_live": "掃除方行",
    "board_status_failed": "局敗",
    "board_status_clear": "方域已清",
    "rank_subtitle": "本地戰績先示，雲端隨後並合。",
    "rank_empty_marker": "無訊",
    "result_retry_tip": "按 R 即重開，或返廳。",
})

_ES = _locale({"title": "Buscaminas", "language": "Idioma"})
_FR = _locale({"title": "Démineur", "language": "Langue"})
_DE = _locale({"title": "Minesweeper", "language": "Sprache"})
_PT = _locale({"title": "Campo Minado", "language": "Idioma"})
_RU = _locale({"title": "Сапёр", "language": "Язык"})
_JA = _locale({"title": "マインスイーパー", "language": "言語"})
_KO = _locale({"title": "지뢰찾기", "language": "언어"})
_AR = _locale({"title": "كاسحة الألغام", "language": "اللغة"})
_HI = _locale({"title": "माइनस्वीपर", "language": "भाषा"})
_IT = _locale({"title": "Campo minato", "language": "Lingua"})

TEXTS = {
    "zh": _ZH,
    "zh-TW": _ZH_TW,
    "en": _EN,
    "ja": _JA,
    "ko": _KO,
    "es": _ES,
    "fr": _FR,
    "de": _DE,
    "pt": _PT,
    "ru": _RU,
    "ar": _AR,
    "hi": _HI,
    "it": _IT,
    "lzh": _LZH,
}

LANG_OPTIONS = [
    ("zh", "简体中文"),
    ("zh-TW", "繁体中文"),
    ("en", "English"),
    ("ja", "日本語"),
    ("ko", "한국어"),
    ("es", "Español"),
    ("fr", "Français"),
    ("de", "Deutsch"),
    ("pt", "Português"),
    ("ru", "Русский"),
    ("ar", "العربية"),
    ("hi", "हिन्दी"),
    ("it", "Italiano"),
    ("lzh", "文言文"),
]

_current_lang = "zh"

_LEGACY_LANG_MAP = {
    "zt": "zh-TW",
    "wy": "lzh",
}


def _normalize_lang(lang: str) -> str:
    return lang if lang in TEXTS else _LEGACY_LANG_MAP.get(lang, "zh")


def load_lang() -> None:
    global _current_lang
    try:
        if os.path.exists(_LANG_FILE):
            with open(_LANG_FILE, "r", encoding="utf-8") as lang_file:
                lang = lang_file.read().strip()
            _current_lang = _normalize_lang(lang)
    except OSError:
        _current_lang = "zh"


def save_lang(lang: str) -> None:
    global _current_lang
    lang = _normalize_lang(lang)
    _current_lang = lang
    os.makedirs(_DATA_DIR, exist_ok=True)
    with open(_LANG_FILE, "w", encoding="utf-8") as lang_file:
        lang_file.write(lang)


def t(key: str, *args) -> str:
    text = TEXTS.get(_current_lang, TEXTS["zh"]).get(key, TEXTS["zh"].get(key, key))
    return text.format(*args) if args else text


def get_lang() -> str:
    return _current_lang


load_lang()
